name: Build and Push to Self-Hosted Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        # Fix: Tell Tailscale to not interfere with public DNS lookups.
        args: --accept-dns=false

    - name: Configure Trust for Docker and Java
      run: |
        # Create a temporary file with the certificate content
        echo "${{ secrets.REGISTRY_CA_CERT }}" > registry-ca.crt

        # 1. Configure Docker's trust store (for docker login and native build)
        echo "--- Configuring Docker Trust ---"
        sudo mkdir -p /etc/docker/certs.d/100.109.96.15
        sudo cp registry-ca.crt /etc/docker/certs.d/100.109.96.15/ca.crt

        # 2. Configure the JVM's trust store (for Jib push)
        echo "--- Configuring Java Keystore Trust ---"
        # The default password for the cacerts keystore is 'changeit'
        sudo $JAVA_HOME/bin/keytool -import -trustcacerts -noprompt \
          -keystore $JAVA_HOME/lib/security/cacerts \
          -storepass changeit \
          -alias selfsigned-registry-ca \
          -file registry-ca.crt

    - name: Debug
      run: |
        echo "--- Debug ---"
        cat /etc/resolv.conf
        cat /etc/hosts
        ping registry.local.mikecarr.net
        ping 10.0.1.201

    # Login to the TAILSCALE IP
    - name: Login to Self-Hosted Registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.local.mikecarr.net -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        
    - name: Build and Push Native Image
      run: |
        # Push to the TAILSCALE IP
        mvn clean package \
          -Dquarkus.package.type=native \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=100.104.88.57:8082 \
          -Dquarkus.container-image.group=mcarr \
          -Dquarkus.native.additional-build-args=-march=x86-64
          -Dquarkus.container-image.tag=${{ github.sha }}-native