# .github/workflows/build-deploy.yml
name: Build and Deploy via Tailscale

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:github-actions
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Login to Nexus via Tailscale
      run: |
        echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 100.64.1.5:5001 \
          -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
        
    - name: Build and Push
      run: |
        mvn clean package \
          -Dquarkus.container-image.registry=100.64.1.5:5001 \
          -Dquarkus.container-image.insecure=true \
          -Dquarkus.container-image.tag=${{ github.sha }}