name: Build and Push to Self-Hosted Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    # Install the CA cert for the correct TAILSCALE IP
    - name: Install custom CA Certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/100.104.88.57
        echo "${{ secrets.REGISTRY_CA_CERT }}" | sudo tee /etc/docker/certs.d/100.104.88.57/ca.crt

    # Login to the TAILSCALE IP
    - name: Login to Self-Hosted Registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login 100.104.88.57 -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        
    - name: Build and Push Native Image
      run: |
        # Push to the TAILSCALE IP
        mvn clean package \
          -Dquarkus.package.type=native \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=100.104.88.57 \
          -Dquarkus.container-image.group=mcarr \
          -Dquarkus.container-image.tag=${{ github.sha }}-native