name: Build and Push with Self-Hosted Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    # ======================================================================
    # NEW DIAGNOSTIC STEPS
    # ======================================================================
    - name: Verify Tailscale Connection
      run: |
        echo "--- Waiting for Tailscale to start ---"
        sleep 5 # Give the daemon a moment to stabilize

        echo "--- Running tailscale status ---"
        tailscale status

        echo "--- Pinging the registry server via Tailscale ---"
        tailscale ping 10.0.1.140

    - name: Install custom CA Certificate
      run: |
        sudo mkdir -p /etc/docker/certs.d/10.0.1.140
        echo "${{ secrets.REGISTRY_CA_CERT }}" | sudo tee /etc/docker/certs.d/10.0.1.140/ca.crt

    - name: Login to Self-Hosted Registry
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login 10.0.1.140 -u "${{ secrets.REGISTRY_USER }}" --password-stdin
        
    - name: Build and Push Native Image
      run: |
        mvn clean package \
          -Dquarkus.package.type=native \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=10.0.1.140 \
          -Dquarkus.container-image.group=mcarr \
          -Dquarkus.container-image.tag=${{ github.sha }}-native