name: Build and Deploy Native Image via Tailscale

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
        args: --accept-dns=false
        
    # CRITICAL: Configure the Docker daemon to trust your insecure registry
    - name: Configure Docker for insecure registry
      run: |
        sudo mkdir -p /etc/docker
        echo '{"insecure-registries":["100.104.88.57:5001"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        
    # CRITICAL: Log the Docker daemon into your registry
    - name: Login to Nexus
      run: |
        echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 100.104.88.57:5001 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
        
    - name: Build and Push Native Image
      run: |
        # We connect using the public domain name.
        # Tailscale DNS resolves this to the private IP.
        # No insecure flags needed!
        docker login registry.yourdomain.com -u "${{ secrets.NEXUS_USERNAME }}" -p "${{ secrets.NEXUS_PASSWORD }}"
        
        mvn clean package \
          -Dquarkus.package.type=native \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=registry.local.mikecarr.net \
          -Dquarkus.container-image.group=mcarr \
          -Dquarkus.container-image.tag=${{ github.sha }}-native